### PR TITLE
fix: skip folded lines

### LINKED ISSUE #27: Startup slow on extremely large files
Hi @lukas-reineke!

When opening a c source file of 600,000 lines (https://github.com/latex-lsp/tree-sitter-latex/blob/master/src/parser.c), I noticed a startup time of 27,138 milliseconds. 7576 ms of these were due to VimEnter autocmds. When I removed the `require('virt-column').setup({})` line from my config, the VimEnter time was around 4 ms.

I get that this normally isn't a problem, but I was wondering if it would be possible to just draw the virtual column line for just the current viewport (I don't know if this is the right word, but I mean the lines currently visible). This would be more like the 'vim-way' of viewing a file.

Let me know what you think! 

Thanks in advance for looking at this issue,
Yochem

### PR DESCRIPTION
**Pull request by yehuohan**
This PR is to skip folded lines to fix https://github.com/lukas-reineke/virt-column.nvim/issues/27

### CODE REVIEW

**Review by lukas-reineke — APPROVED** [review]
Thanks :rocket:

File: lua/virt-column/init.lua [hunk 1]
```diff
@@ -92,6 +93,13 @@ local init = function()
                         })
                     end
                 end
+                local fold_end = vim.api.nvim_win_call(win, function()
+                    return vim.fn.foldclosedend(i)
```
Comment (lukas-reineke) [inline lua/virt-column/init.lua:98]:
```suggestion
                    ---@diagnostic disable-next-line: redundant-return-value
                    return vim.fn.foldclosedend(i)
```

Looks like the types for stable are not correct here :thinking: 
Can you add this to ignore the error?

Comment (yehuohan) [reply lua/virt-column/init.lua:98]: Of course sure! Had commited.
